// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "أحمد علي",
    email: "ahmed.ali@example.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0944123456",
    subjects: ["رياضيات", "هندسة"],
    classes: ["ابتدائي", "إعدادي"],
    address: "دمشق، سوريا",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "محمد حسن",
    email: "mohammed.hassan@example.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0944234567",
    subjects: ["فيزياء", "كيمياء"],
    classes: ["إعدادي", "ثانوي"],
    address: "حلب، سوريا",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "يوسف عبد الله",
    email: "youssef.abdullah@example.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0944345678",
    subjects: ["أحياء"],
    classes: ["ثانوي"],
    address: "حمص، سوريا",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "سارة محمد",
    email: "sara.mohammed@example.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0944456789",
    subjects: ["تاريخ"],
    classes: ["ابتدائي", "إعدادي", "ثانوي"],
    address: "اللاذقية، سوريا",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "علياء سامي",
    email: "alia.sami@example.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "0944567890",
    subjects: ["موسيقى", "تاريخ"],
    classes: ["ابتدائي", "إعدادي"],
    address: "درعا، سوريا",
  },
];

export const studentsData = [
  { id: 1, studentId: "S2025001", name: "محمد الأحمد", email: "mohammed.ahmed@example.com", photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945123456", grade: 5, class: "ابتدائي", address: "شارع النصر، دمشق، سوريا" },
  { id: 2, studentId: "S2025002", name: "أحمد مصطفى", email: "ahmed.mostafa@example.com", photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945234567", grade: 5, class: "ابتدائي", address: "شارع الثورة، دمشق، سوريا" },
  { id: 3, studentId: "S2025003", name: "ليلى عبد الرحمن", email: "layla.abdulrahman@example.com", photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945345678", grade: 5, class: "ابتدائي", address: "حي الشعلان، حلب، سوريا" },
  { id: 4, studentId: "S2025004", name: "يوسف علي", email: "yousef.ali@example.com", photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945456789", grade: 5, class: "ابتدائي", address: "شارع خالد بن الوليد، حمص، سوريا" },
  { id: 5, studentId: "S2025005", name: "سارة خليل", email: "sara.khalil@example.com", photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945567890", grade: 5, class: "إعدادي", address: "حي الجلاء، اللاذقية، سوريا" },
  { id: 6, studentId: "S2025006", name: "علي حسن", email: "ali.hassan@example.com", photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945678901", grade: 5, class: "إعدادي", address: "شارع الثورة دمشق، سوريا" },
  { id: 7, studentId: "S2025007", name: "مريم فهد", email: "mariam.fahd@example.com", photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945789012", grade: 5, class: "ثانوي", address: "حي الحمدانية، حلب، سوريا" },
  { id: 8, studentId: "S2025008", name: "خالد محمود", email: "khaled.mahmoud@example.com", photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945890123", grade: 5, class: "ثانوي", address: "شارع الوحدة، حمص، سوريا" },
  { id: 9, studentId: "S2025009", name: "فاطمة علي", email: "fatima.ali@example.com", photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945901234", grade: 5, class: "ثانوي", address: "حي الرمل، اللاذقية، سوريا" },
  { id: 10, studentId: "S2025010", name: "حمزة سعيد", email: "hamza.saeed@example.com", photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200", phone: "0945012345", grade: 5, class: "ثانوي", address: "شارع الجمهورية، دمشق، سوريا" },
];




export const parentsData = [
  {
    id: 1,
    name: "أحمد العلي",
    students: ["خالد العلي"],
    email: "ahmad.ali@example.com",
    phone: "0944001122",
    address: "حلب - حي الشعار",
  },
  {
    id: 2,
    name: "سعاد الحموي",
    students: ["رنا الحموي"],
    email: "souad.hamwi@example.com",
    phone: "0933557799",
    address: "دمشق - المزة",
  },
  {
    id: 3,
    name: "محمود درويش",
    students: ["ليان درويش"],
    email: "mahmoud.darwish@example.com",
    phone: "0999887766",
    address: "حمص - الوعر",
  },
  {
    id: 4,
    name: "جمال إبراهيم",
    students: ["يزن إبراهيم", "نور إبراهيم"],
    email: "jamal.ibrahim@example.com",
    phone: "0955332211",
    address: "اللاذقية - المشروع العاشر",
  },
  {
    id: 5,
    name: "ليلى خليل",
    students: ["سارة خليل"],
    email: "leila.khalil@example.com",
    phone: "0944223344",
    address: "طرطوس - الكورنيش",
  },
  {
    id: 6,
    name: "منى عواد",
    students: ["يوسف عواد"],
    email: "mona.awad@example.com",
    phone: "0933005566",
    address: "إدلب - سرمين",
  },
  {
    id: 7,
    name: "خالد الحسن",
    students: ["رامي الحسن", "مها الحسن"],
    email: "khaled.hassan@example.com",
    phone: "0999332211",
    address: "ريف حلب - إعزاز",
  },
  {
    id: 8,
    name: "هيام عثمان",
    students: ["آية عثمان"],
    email: "hiyam.othman@example.com",
    phone: "0955667788",
    address: "حماة - حي الأربعين",
  },
  {
    id: 9,
    name: "فادي الطرابيشي",
    students: ["محمد الطرابيشي", "سوسن الطرابيشي"],
    email: "fadi.tarabishi@example.com",
    phone: "0944332211",
    address: "دمشق - برزة",
  },
  {
    id: 10,
    name: "نادر رمضان",
    students: ["جود رمضان"],
    email: "nader.ramadan@example.com",
    phone: "0999221133",
    address: "درعا - البلد",
  },
];


export const subjectsData = [
  {
    id: 1,
    name: "رياضيات",
    teachers: ["أحمد علي"],
  },
  {
    id: 2,
    name: "لغة إنجليزية",
    teachers: ["سارة محمد"],
  },
  {
    id: 3,
    name: "فيزياء",
    teachers: ["محمد حسن"],
  },
  {
    id: 4,
    name: "كيمياء",
    teachers: ["محمد حسن"],
  },
  {
    id: 5,
    name: "أحياء",
    teachers: ["يوسف عبد الله"],
  },
  {
    id: 6,
    name: "تاريخ",
    teachers: ["سارة محمد", "علياء سامي"],
  },
  {
    id: 7,
    name: "جغرافيا",
    teachers: ["سارة محمد"],
  },
  {
    id: 8,
    name: "فنون",
    teachers: ["علياء سامي"],
  },
  {
    id: 9,
    name: "موسيقى",
    teachers: ["علياء سامي"],
  },
  {
    id: 10,
    name: "أدب عربي",
    teachers: ["سارة محمد"],
  },
];


export const classesData = [
  {
    id: 1,
    name: "الصف الأول",
    capacity: 20,
    grade: 1,
    supervisor: "أحمد علي",
  },
  {
    id: 2,
    name: "الصف الثاني",
    capacity: 22,
    grade: 2,
    supervisor: "محمد حسن",
  },
  {
    id: 3,
    name: "الصف الثالث",
    capacity: 20,
    grade: 3,
    supervisor: "يوسف عبد الله",
  },
  {
    id: 4,
    name: "الصف الرابع",
    capacity: 18,
    grade: 4,
    supervisor: "سارة محمد",
  },
  {
    id: 5,
    name: "الصف الخامس",
    capacity: 16,
    grade: 5,
    supervisor: "علياء سامي",
  },
  {
    id: 6,
    name: "الصف السادس",
    capacity: 20,
    grade: 6,
    supervisor: "منى درويش",
  },
  {
    id: 7,
    name: "الصف السابع",
    capacity: 18,
    grade: 7,
    supervisor: "خالد العلي",
  },
  {
    id: 8,
    name: "الصف الثامن",
    capacity: 22,
    grade: 8,
    supervisor: "ليلى خليل",
  },
  {
    id: 9,
    name: "الصف التاسع",
    capacity: 18,
    grade: 9,
    supervisor: "هيام عثمان",
  },
  {
    id: 10,
    name: "الصف العاشر",
    capacity: 20,
    grade: 10,
    supervisor: "فادي الطرابيشي",
  },
  {
    id: 11,
    name: "الصف الحادي عشر",
    capacity: 25,
    grade: 11,
    supervisor: "سارة محمد",
  },
  {
    id: 12,
    name: "البكالوريا",
    capacity: 30,
    grade: 12,
    supervisor: "محمد حسن",
  },
];




export const examsData = [
  {
    id: 1,
    subject: "رياضيات",
    class: "الصف الأول",
    teacher: "أحمد علي",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "لغة إنجليزية",
    class: "الصف الثاني",
    teacher: "سارة محمد",
    date: "2025-01-02",
  },
  {
    id: 3,
    subject: "علوم",
    class: "الصف الثالث",
    teacher: "محمد حسن",
    date: "2025-01-03",
  },
  {
    id: 4,
    subject: "تربية اجتماعية",
    class: "الصف الرابع",
    teacher: "سارة محمد",
    date: "2025-01-04",
  },
  {
    id: 5,
    subject: "فنون",
    class: "الصف الخامس",
    teacher: "علياء سامي",
    date: "2025-01-05",
  },
  {
    id: 6,
    subject: "موسيقى",
    class: "الصف السادس",
    teacher: "علياء سامي",
    date: "2025-01-06",
  },
  {
    id: 7,
    subject: "تاريخ",
    class: "الصف السابع",
    teacher: "سارة محمد",
    date: "2025-01-07",
  },
  {
    id: 8,
    subject: "جغرافيا",
    class: "الصف الثامن",
    teacher: "سارة محمد",
    date: "2025-01-08",
  },
  {
    id: 9,
    subject: "فيزياء",
    class: "الصف التاسع",
    teacher: "محمد حسن",
    date: "2025-01-09",
  },
  {
    id: 10,
    subject: "كيمياء",
    class: "الصف العاشر",
    teacher: "محمد حسن",
    date: "2025-01-10",
  },
];


export const assignmentsData = [
  {
    id: 1,
    subject: "رياضيات",
    class: "الصف الأول",
    teacher: "أحمد علي",
    dueDate: "2025-01-05",
  },
  {
    id: 2,
    subject: "لغة إنجليزية",
    class: "الصف الثاني",
    teacher: "سارة محمد",
    dueDate: "2025-01-06",
  },
  {
    id: 3,
    subject: "علوم",
    class: "الصف الثالث",
    teacher: "محمد حسن",
    dueDate: "2025-01-07",
  },
  {
    id: 4,
    subject: "تربية اجتماعية",
    class: "الصف الرابع",
    teacher: "سارة محمد",
    dueDate: "2025-01-08",
  },
  {
    id: 5,
    subject: "فنون",
    class: "الصف الخامس",
    teacher: "علياء سامي",
    dueDate: "2025-01-09",
  },
  {
    id: 6,
    subject: "موسيقى",
    class: "الصف السادس",
    teacher: "علياء سامي",
    dueDate: "2025-01-10",
  },
  {
    id: 7,
    subject: "تاريخ",
    class: "الصف السابع",
    teacher: "سارة محمد",
    dueDate: "2025-01-11",
  },
  {
    id: 8,
    subject: "جغرافيا",
    class: "الصف الثامن",
    teacher: "سارة محمد",
    dueDate: "2025-01-12",
  },
  {
    id: 9,
    subject: "فيزياء",
    class: "الصف التاسع",
    teacher: "محمد حسن",
    dueDate: "2025-01-13",
  },
  {
    id: 10,
    subject: "كيمياء",
    class: "الصف العاشر",
    teacher: "محمد حسن",
    dueDate: "2025-01-14",
  },
];


export const resultsData = [
  {
    id: 1,
    subject: "الرياضيات",
    class: "الصف الأول",
    teacher: "أحمد العلي",
    student: "محمد خالد",
    date: "2025-01-01",
    type: "امتحان",
    score: 92,
  },
  {
    id: 2,
    subject: "اللغة العربية",
    class: "الصف الثاني",
    teacher: "سعاد إبراهيم",
    student: "ليان يوسف",
    date: "2025-01-02",
    type: "وظيفة",
    score: 85,
  },
  {
    id: 3,
    subject: "العلوم",
    class: "الصف الثالث",
    teacher: "مروان حسن",
    student: "خالد رامي",
    date: "2025-01-03",
    type: "امتحان",
    score: 78,
  },
  {
    id: 4,
    subject: "التربية الاجتماعية",
    class: "الصف الرابع",
    teacher: "نسرين عمر",
    student: "نور علاء",
    date: "2025-01-04",
    type: "وظيفة",
    score: 88,
  },
  {
    id: 5,
    subject: "التربية الفنية",
    class: "الصف الخامس",
    teacher: "ماهر عبدو",
    student: "رهف سامر",
    date: "2025-01-05",
    type: "امتحان",
    score: 95,
  },
  {
    id: 6,
    subject: "الموسيقا",
    class: "الصف السادس",
    teacher: "حسن مصطفى",
    student: "زياد أنور",
    date: "2025-01-06",
    type: "وظيفة",
    score: 82,
  },
  {
    id: 7,
    subject: "التاريخ",
    class: "الصف السابع",
    teacher: "منى فؤاد",
    student: "إسراء هيثم",
    date: "2025-01-07",
    type: "امتحان",
    score: 90,
  },
  {
    id: 8,
    subject: "الجغرافيا",
    class: "الصف الثامن",
    teacher: "رامي خالد",
    student: "أدهم وليد",
    date: "2025-01-08",
    type: "وظيفة",
    score: 76,
  },
  {
    id: 9,
    subject: "الفيزياء",
    class: "الصف التاسع",
    teacher: "سهى أحمد",
    student: "سارة مازن",
    date: "2025-01-09",
    type: "امتحان",
    score: 89,
  },
  {
    id: 10,
    subject: "الكيمياء",
    class: "الصف العاشر",
    teacher: "وائل جابر",
    student: "رامي حسين",
    date: "2025-01-10",
    type: "وظيفة",
    score: 91,
  },
];



export const eventsData = [
  {
    id: 1,
    title: "رحلة إلى البحيرة",
    class: "الصف الأول",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "نزهة",
    class: "الصف الثاني",
    date: "2025-01-02",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "رحلة إلى الشاطئ",
    class: "الصف الثالث",
    date: "2025-01-03",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "زيارة المتحف",
    class: "الصف الرابع",
    date: "2025-01-04",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "حفلة انشادية",
    class: "الصف الخامس",
    date: "2025-01-05",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "مسابقة برمجة",
    class: "الصف الأول",
    date: "2025-01-06",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "رحلة إلى البحيرة",
    class: "الصف الثاني",
    date: "2025-01-07",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "سباق الدراجات",
    class: "الصف الثالث",
    date: "2025-01-08",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "معرض فني",
    class: "الصف الرابع",
    date: "2025-01-09",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "بطولة رياضية",
    class: "الصف الخامس",
    date: "2025-01-10",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "عن اختبار الرياضيات للصف الرابع",
    class: "الصف الرابع",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "عن اختبار الرياضيات للصف الثالث",
    class: "الصف الثالث",
    date: "2025-01-02",
  },
  {
    id: 3,
    title: "عن اختبار الرياضيات للصف الثالث",
    class: "الصف الثالث",
    date: "2025-01-03",
  },
  {
    id: 4,
    title: "عن اختبار الرياضيات للصف السادس",
    class: "الصف السادس",
    date: "2025-01-04",
  },
  {
    id: 5,
    title: "عن اختبار الرياضيات للصف الثامن",
    class: "الصف الثامن",
    date: "2025-01-05",
  },
  {
    id: 6,
    title: "عن اختبار الرياضيات للصف الثاني",
    class: "الصف الثاني",
    date: "2025-01-06",
  },
  {
    id: 7,
    title: "عن اختبار الرياضيات للصف الرابع",
    class: "الصف الرابع",
    date: "2025-01-07",
  },
  {
    id: 8,
    title: "عن اختبار الرياضيات للصف الرابع",
    class: "الصف الرابع",
    date: "2025-01-08",
  },
  {
    id: 9,
    title: "عن اختبار الرياضيات للصف الثالث",
    class: "الصف الثالث",
    date: "2025-01-09",
  },
  {
    id: 10,
    title: "عن اختبار الرياضيات للصف الأول",
    class: "الصف الأول",
    date: "2025-01-10",
  },
];



// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "رياضيات",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "إنجليزي",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "أحياء",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "فيزياء",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "كيمياء",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "تاريخ",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "إنجليزي",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "أحياء",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "فيزياء",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },
  {
    title: "تاريخ",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "رياضيات",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "أحياء",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },
  {
    title: "كيمياء",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "تاريخ",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 14, 14, 45), // ✅ تم التصحيح
  },
  {
    title: "إنجليزي",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "أحياء",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "فيزياء",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },
  {
    title: "تاريخ",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "رياضيات",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "إنجليزي",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },
  {
    title: "فيزياء",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "كيمياء",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "تاريخ",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];
